popf: patch src to fix build
lopsided98/nix-ros-overlay pull request #258
Opened 2023-04-01 07:53 UTC by movefasta

Closes #255

2023-04-01 08:34 UTC, wentasah approved these changes
This looks good. The perl dependency should probably be added upstream to https://github.com/fmrico/popf/blob/master/package.xml, but here we still need to patch the shebang so we cannot avoid the override.

2023-04-01 09:45 UTC, movefasta commented
> The perl dependency should probably be added upstream to https://github.com/fmrico/popf/blob/master/package.xml.

There's no perl package in [rosdistro index](https://index.ros.org/search/?term=perl&section=deps). I doubt if we should add it there due a rare using perl in ROS ecosystem. So overlaying in our particular case maybe quite enough.

2023-04-01 10:00 UTC, wentasah commented
Right. I think ROS packages can depend on distribution packages, but then the package must be mentioned in https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml. And `perl` is not there, so adding it to `package.xml` makes no sense. Thanks.

2023-04-02 04:01 UTC, lopsided98 requested changes

2023-04-02 04:01 UTC, lopsided98 commented on distros/distro-overlay.nix
> +      nativeBuildInputs ? [], ...
```suggestion
      nativeBuildInputs ? [], postPatch ? "", ...
```

2023-04-02 15:34 UTC, merged