catkin: patch to account for NIXPKGS_CMAKE_PREFIX_PATH
lopsided98/nix-ros-overlay pull request #500
Opened 2024-10-07 18:19 UTC by kjeremy

Alternative to #497. Heavy handed but:

`nix build .#noetic.pluginlib` works.

`nix develop .#noetic.pluginlib` and manually invoking `cmake` to build works.

Fixes #491

2024-10-07 18:19 UTC, kjeremy commented
@wentasah

2024-10-08 12:19 UTC, wentasah requested changes
This will probably work well enough. Few suggestions below.

2024-10-08 12:19 UTC, wentasah commented on distros/ros1-overlay.nix
> +      patch -p1 < ${cmakePatch}
This would be IMHO simpler:
```nix
patches = patches ++ [ ./catkin-nixpkgs-prefix-path.patch ];
```

2024-10-08 12:19 UTC, wentasah commented on distros/catkin-nixpkgs-prefix-path.patch
> ++string(REPLACE ":" ";" CMAKE_PREFIX_PATH $ENV{NIXPKGS_CMAKE_PREFIX_PATH})
Wrap it in `if(NOT DEFINED CMAKE_PREFIX_PATH)` so that the user can always override it, if needed.

2024-10-08 14:00 UTC, wentasah approved these changes
This is better :-) Thanks.

2024-10-10 16:04 UTC, kjeremy commented
It turns out that this doesn't fix everything. `.#noetic.roslint` fails and `sdformat` too

2024-10-16 12:19 UTC, kjeremy commented
@lopsided98 can this be merged so noetic works again?

2024-10-16 23:39 UTC, merged