Update meta.description and add meta.homepage if missing
lopsided98/nix-ros-overlay pull request #534
Opened 2024-12-06 19:19 UTC by Pandapip1

2024-12-07 18:54 UTC, lopsided98 requested changes
You need to evaluate all these packages, would have caught these issues and any others that I missed.

2024-12-07 18:54 UTC, lopsided98 commented on pkgs/bloom/default.nix
> +    fullDescription = "A release automation tool which makes releasing catkin (http://ros.org/wiki/catkin) packages easier";
`fullDescription` doesn't exist, it's `longDescription`

2024-12-07 18:54 UTC, lopsided98 commented on pkgs/colcon/python-setup-py.nix
> +    description = "Extension for colcon-core to identify packages from setup.py files";
Duplicate attribute, the other needs to be renamed to `longDescription`.

2024-12-07 18:54 UTC, lopsided98 commented on pkgs/gazebo/gz-cmake/generic.nix
> +    description = "A set of CMake modules that are used by the C++-based Gazebo projects";
Did you want to remove the indefinite article here like the rest?

2024-12-14 20:11 UTC, Pandapip1 commented
CI is failing on develop.

2024-12-15 17:32 UTC, merged