remove --as-needed propagated flag from backward-ros
lopsided98/nix-ros-overlay pull request #550
Opened 2024-12-17 14:19 UTC by liarokapisv

Fixes https://github.com/lopsided98/nix-ros-overlay/issues/541

Removing the flag relieves the linker in dependent packages like `ros-moveit-*` with many dependencies, since it would otherwise need to search all propagated libraries for symbols.

2024-12-17 20:27 UTC, wentasah requested changes
Can you make the sed expression more understandable as suggested below? Also add a comment explaining why this is needed. A sentence similar to your commit message should be sufficient.

And it seems that this breaks backward-ros in noetic. So this should go into `ros2-overlay.nix`.

2024-12-17 20:42 UTC, wentasah commented
Otherwise this looks good. It [fixed 45 packages](https://hydra.iid.ciirc.cvut.cz/eval/1397?compare=develop-all-x86_64&full=0#tabs-now-succeed). 

I was wondering why the `--as-needed` is there at all. It was added in [this commit](https://github.com/pal-robotics/backward_ros/commit/485c6e9ef9bf37e60abc0a967db77708f910ddf2#diff-28ddc9309d8ab162dc9c2ca02fa5ca35cea621012637ccf597f79fb4126c87f6R14), which seems to be the first ROS-related commit in the repo. Maybe, we could try submitting a PR removing that line at upstream. I guess it was some hack needed back in 2017, which may not be relevant today.

2024-12-17 22:07 UTC, liarokapisv commented
What is more baffling to me is why this worked in older (post-Summer) nix-ros-overlay builds. The build worked and the `--as-needed` flag was not actually propagated to dependencies. Maybe a cmake version bump changed the behavior?

2024-12-18 08:13 UTC, wentasah approved these changes
LGTM. Thanks!

2024-12-31 11:06 UTC, liarokapisv commented
Hi there! Is there anything else I can do to help with the merge?

2024-12-31 12:40 UTC, okvik commented
Thanks for this, it fixes a bunch of packages that I use.

2025-01-01 18:39 UTC, merged